# Generated by Django 3.1.7 on 2021-03-17 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('users_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('profilePicture', models.CharField(max_length=255)),
                ('emailAddress', models.CharField(max_length=255)),
                ('favoriteCoin', models.CharField(max_length=50)),
            ],
        ),
    ]
